---

- name: install env_functions.sh
  file:
    src: "env_functions_v2.sh"
    dest: "/home/{{ lookup('env','USER') }}/functions/env_functions_v2.sh"
    owner: "{{ lookup('env','USER') }}"
    group: "{{ lookup('env','USER') }}"
    mode: "0644"
