---
# https://support.yubico.com/hc/en-us/articles/360016649039-Installing-Yubico-Software-on-Linux
# todo: add signing key to ensure it works properly
- name: Add Yubico repo
  apt_repository:
    repo: ppa:yubico/stable
    filename: yubico
    state: present
    update_cache: True
    validate_certs: True

- name: Install Yubico-manager and personalization-gui package
  apt:
    state: latest
    pkg:
      - yubikey-manager
      - yubikey-personalization-gui
