# Enable AI-powered fixes and PR summaries
engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
        - python

exclude_paths:
  - "test/**"
  - "**/*.test.js"
  - "node_modules/**"
  - "dist/**"
  - "build/**"

# Enable new AI features
suggested_fixes:
  enabled: true

ai_enhanced_comments:
  enabled: true

pull_request_summary:
  enabled: true
