---
- name: Playbook desktop start
  hosts: all
  become: true
  become_user: root
  become_method: sudo
  gather_facts: true
  pre_tasks:
    - name: resolve remote user facts
      ansible.builtin.include_tasks: resolve_user.yml
      tags: always

  roles:
    - apt-sources-ubc
    - alacritty
    - base
    - aws
    - brave
    - chrome
    - dev-tools
    - docker-cli-only
    # - docker-desktop-dependency
    - env             # executes as local user, not root
    - firefox
    - fzf             # executes as local user, not root
    - gh_cli
    - git
    - hashicorp
    - keepassxc
    - kubectl
    - lazydocker
    - microsoft
    - mullvad
    - neovim
    - opera
    - signal-desktop
    - sublime-text
    - trivy
    - unattended-upgrade-override
    - vagrant-libvirt
    - vim             # executes as local user, not root
    - wireshark
    - yubico
    - test-vars
    - disable-local-dns
