---
- name: Playbook desktop start
  hosts: all
  #user:
  become: True
  become_user: root
  become_method: sudo
  gather_facts: True
  #tasks:
  #- include_tasks: tasks/main.yml
  
  roles:
    - role: aws-cli
    - role: base
    - role: brave
    - role: chrome
    - role: docker
    - role: edge
    - role: hashicorp
    - role: keepassxc
    - role: signal-desktop
    - role: ufw
