---
- name: Playbook desktop start
  hosts: all
  become: true
  become_user: root
  become_method: sudo
  gather_facts: true
  vars_files:
    - vars.yml

  roles:
    - auto-update
    - base
    - aws
    - brave
    - chrome
    # - docker-cli-only
    - docker-desktop-dependency
    - gh_cli
    - hashicorp
    - keepassxc
    - kubectl
    - microsoft
    - mullvad
    - opera
    - signal-desktop
    - sublime-text
    - trivy
    - role: vim
      become: false
    - role: env
      become: false
    - disable-local-dns
    # - yubico
