---
- name: Playbook desktop start
  hosts: all
  #user:
  become: True
  become_user: root
  become_method: sudo
  gather_facts: False
  #tasks:
  #- include_tasks: tasks/main.yml
  
  roles:
    #- role: base
    #- role: chrome
    #- role: keepassxc
    #- role: signal-desktop
    #- role: brave
    #- role: ufw
    #- role: geerlingguy.node_exporter
    - role: jradtilbrook.grafana
