---
- name: Playbook desktop start
  hosts: all
  become: true
  become_user: root
  become_method: sudo
  gather_facts: true
  #tasks:
  #- include_tasks: tasks/main.yml
  pre_tasks:
  - name: Set home directory fact
    set_fact:
      home_dir: "{{ ansible_env['PWD'] }}"

  - name: Set local user fact
    set_fact:
      local_user: "{{ ansible_user }}"

  - name: Get user's primary group name
    command: "id -gn {{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
    register: global_primary_group
    changed_when: false

  - name: Set user's primary group fact
    set_fact:
      local_user_primary_group: "{{ global_primary_group.stdout }}"

  roles:
    - auto-update
    - base
    - aws
    - brave
    - chrome
    - docker-cli-only
    - docker-desktop-dependency
    - gh_cli
    - hashicorp
    - keepassxc
    - kubectl
    - microsoft
    - opera
    - signal-desktop
    - sublime-text
    - trivy
    - ufw
    - role: vim
      become: false
    - role: env
      become: false
    - disable-local-dns
    # - yubico
