---
- name: Playbook desktop start
  hosts: all
  become: true
  become_user: root
  become_method: sudo
  gather_facts: true
  #tasks:
  #- include_tasks: tasks/main.yml

  roles:
    - base
    - aws-cli
    - brave
    - chrome
    - docker
    - gh_cli
    - hashicorp
    - keepassxc
    - kubectl
    - lens
    - microsoft
    - opera
    - signal-desktop
    - ufw
    - role: vim
      become: false
    - role: env
      become: false
    - disable-local-dns
    # - yubico
