---
- name: Playbook desktop start
  hosts: all
  become: true
  become_user: root
  become_method: sudo
  gather_facts: true
  vars_files:
    - vars.yml

  roles:
    - apt-sources-ubc
    - aws
    - base
    - brave
    - chrome
    - dev-tools
    # - docker-cli-only
    - docker-desktop-dependency
    - env
    - fzf
    - gh_cli
    - git
    - hashicorp
    - keepassxc
    - kubectl
    - microsoft
    - mullvad
    - opera
    - signal-desktop
    - sublime-text
    - trivy
    - unattended-upgrade-override
    - vim
    - disable-local-dns
    # - yubico
