---
- name: Playbook desktop start
  hosts: all
  #user:
  become: True
  become_user: root
  become_method: sudo
  gather_facts: True
  #tasks:
  #- include_tasks: tasks/main.yml

  roles:
    - base
    - aws-cli
    - brave
    - chrome
#    - docker
    - gh_cli
    - keepassxc
    - kubectl
    - hashicorp
    - microsoft
    - opera
    - signal-desktop
    - vivaldi
    - ufw
    - env
    - vim
    - disable-local-dns
    - ansible-role-docker
    #- yubico
