---
- name: resolve remote user facts
  block:
  - name: Determine local_user via whoami
    ansible.builtin.command: whoami
    become: false
    changed_when: false
    register: whoami_result
    when: local_user is not defined

  - name: Set local_user fact
    ansible.builtin.set_fact:
      local_user: "{{ whoami_result.stdout }}"
    when: local_user is not defined

  - name: Get home_dir via passwd entry for local_user
    ansible.builtin.getent:
      database: passwd
      key: "{{ local_user }}"

  - name: Get local_user_primary_group via group entry for local_user
    ansible.builtin.getent:
      database: group
      key: "{{ ansible_facts.getent_passwd[local_user][2] }}"

  - name: Set derived facts
    ansible.builtin.set_fact:
      home_dir: "{{ ansible_facts.getent_passwd[local_user][4] }}"
      local_user_primary_group: "{{ ansible_facts.getent_group | first }}"

  - name: Display resolved values
    ansible.builtin.debug:
      msg:
        local_user: "{{ local_user }}"
        home_dir: "{{ home_dir }}"
        local_user_primary_group: "{{ local_user_primary_group }}"
  tags: always
