---
- name: "Playbook to test various variables"
  hosts: all
  become: true
  become_method: sudo
  gather_facts: true
  vars_files:
    - vars.yml

  tasks:
    - name: host information
      debug:
        msg: |
          ansible_host: {{ ansible_host }}
          ansible_hostname: {{ ansible_hostname }}
          playbook_dir: {{ playbook_dir }}
          group_names: {{ group_names }}
          ansible_python_version: {{ ansible_python_version }}

    - name: os information
      debug:
        msg: |
          ansible_os_family: {{ ansible_os_family }}
          ansible_distribution: {{ ansible_distribution }}
          ansible_distribution_version: {{ ansible_distribution_version }}
          ansible_distribution_release: {{ ansible_distribution_release }}

    - name: network information
      debug:
        msg: |
          Primary Interface: {{ ansible_default_ipv4.interface }}
          IP Address: {{ ansible_default_ipv4.address }}
          Subnet: {{ ansible_default_ipv4.network }}
          Netmask: {{ ansible_default_ipv4.netmask }}
          All Interfaces: {{ ansible_interfaces }}

    - name: Get user's primary group name
      command: "id -gn {{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
      register: primary_group
      changed_when: false

    - name: Get user's primary group name - set fact (custom var)
      set_fact:
        user_primary_group: "{{ primary_group.stdout }}"

    - name: user information
      debug:
        msg: |
          ansible_env['USER']: {{ ansible_env['USER'] }}
          ansible_env['SUDO_USER']: {{ ansible_env['SUDO_USER'] }}
          ansible_env['SHELL']: {{ ansible_env['SHELL'] }}
          ansible_env['PWD']: {{ ansible_env['PWD'] }}
          ansible_env['HOME']: {{ ansible_env['HOME'] }}
          ansible_user: {{ ansible_user }}
          ansible_user_id: {{ ansible_user_id }}
          ansible_user primary group (custom var): {{ user_primary_group }}

    - name: variables from vars.yaml
      debug:
        msg: |
          home_dir: {{ home_dir }}
          local_user: {{ local_user }}
          local_user_primary_group: {{ local_user_primary_group }}
