---
- name: Add Sublime Text apt repository key
  get_url:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    dest: /usr/share/keyrings/sublimehq-archive.asc
    mode: "0644"
    force: false

- name: Add Sublime Text repo
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/sublimehq-archive.asc] https://download.sublimetext.com/ apt/stable/"
    filename: sublime-text
    state: present
    update_cache: true

- name: Install Sublime Text
  apt:
    name: sublime-text
    state: present
