---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
  changed_when: false

- name: Reset failed state (if any)
  ansible.builtin.command: systemctl reset-failed apt-daily-upgrade.timer
  become: true
  changed_when: false
  failed_when: false

- name: Ensure timer is active
  ansible.builtin.systemd:
    name: apt-daily-upgrade.timer
    state: started
    enabled: true
  become: true
