---
- name: install signal-desktop dependencies
  apt:
    name: "{{ signal_desktop_apt_dependencies }}"
    state: present

- name: install signal GPG key
  apt_key:
    data: "{{ lookup('file', 'signal-apt-key.asc') }}"
    id: DBA36B5181D0C816F630E889D980A17457F6FB06
    state: present
    keyring: /etc/apt/trusted.gpg.d/signal-desktop.gpg

- name: add Signal repo
  apt_repository:
    repo: "{{ signal_desktop_apt_repo }}"
    state: present

- name: install Signal desktop
  apt:
    name: signal-desktop
    state: present
