---
# https://mullvad.net/en/download/vpn/linux
- block:
    - name: Add Mullvad apt repository key
      get_url:
        url: https://repository.mullvad.net/deb/mullvad-keyring.asc
        dest: /usr/share/keyrings/mullvad-keyring.asc
        mode: "0644"
        force: false

    - name: Set Mullvad repo codename
      set_fact:
        mullvad_codename: >-
          {{
            ansible_facts['distribution_release']
            if ansible_facts['distribution_release'] in ['jammy', 'noble']
            else 'noble'
          }}

    - name: Add Mullvad repo
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/mullvad-keyring.asc arch=amd64] https://repository.mullvad.net/deb/stable {{ mullvad_codename }} main"
        filename: mullvad-browser
        state: present
        update_cache: true

    - name: Install Mullvad
      apt:
        name: "mullvad-browser"
        state: present
  tags: ['mullvad']
