---
- block:
    - name: Copy apt configs
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/etc/apt/apt.conf.d/{{ item }}"
        owner: root
        group: root
        mode: '0644'
      loop:
        - 21auto-upgrades-autoclean
        - 51unattended-upgrades-override
        - 52unattended-upgrades-reboot

    - name: Ensure systemd override directory exists
      ansible.builtin.file:
        path: /etc/systemd/system/apt-daily-upgrade.timer.d
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Copy apt-daily-upgrade.timer override
      ansible.builtin.copy:
        src: override.conf
        dest: /etc/systemd/system/apt-daily-upgrade.timer.d/override.conf
        owner: root
        group: root
        mode: '0644'
      notify:
        - Reload systemd
        - Restart apt-daily-upgrade.timer
  tags: ['unattended-upgrade-override']
