---
- block:
    - name: Ensure Microsoft GPG keyring directory exists
      ansible.builtin.file:
        path: /usr/share/keyrings
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Skip download if GPG key already exists
      ansible.builtin.stat:
        path: /usr/share/keyrings/microsoft.gpg
      register: microsoft_gpg_stat

    - name: Download Microsoft Linux signing key (ASCII format)
      ansible.builtin.get_url:
        url: "https://packages.microsoft.com/keys/microsoft.asc"
        dest: /tmp/microsoft.asc
        mode: '0644'
      when: not microsoft_gpg_stat.stat.exists
      register: microsoft_key_download

    - name: Convert Microsoft key to GPG binary format
      ansible.builtin.command:
        cmd: gpg --dearmor -o /usr/share/keyrings/microsoft.gpg /tmp/microsoft.asc
        creates: /usr/share/keyrings/microsoft.gpg
      when: not microsoft_gpg_stat.stat.exists

    - name: Remove temporary ASCII key file
      ansible.builtin.file:
        path: /tmp/microsoft.asc
        state: absent

    - name: Remove obsolete Microsoft key and repo files (if present)
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /usr/share/keyrings/microsoft.asc
        - /etc/apt/sources.list.d/microsoft-edge.list
        - /etc/apt/sources.list.d/vscode.list

    - name: Configure Microsoft Edge repository (.sources format)
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/microsoft-edge.sources
        owner: root
        group: root
        mode: '0644'
        content: |
          Types: deb
          URIs: https://packages.microsoft.com/repos/edge
          Suites: stable
          Components: main
          Architectures: amd64
          Signed-By: /usr/share/keyrings/microsoft.gpg
      register: edge_repo

    - name: Configure Microsoft VS Code repository (.sources format)
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/vscode.sources
        owner: root
        group: root
        mode: '0644'
        content: |
          Types: deb
          URIs: https://packages.microsoft.com/repos/code
          Suites: stable
          Components: main
          Architectures: amd64
          Signed-By: /usr/share/keyrings/microsoft.gpg
      register: vscode_repo

    - name: Update apt cache if repos changed or key was downloaded
      ansible.builtin.apt:
        update_cache: yes
      when: edge_repo.changed or vscode_repo.changed or (microsoft_key_download is defined and microsoft_key_download.changed)

    - name: Install Microsoft Edge and VS Code
      ansible.builtin.apt:
        name:
          - microsoft-edge-stable
          - code
        state: latest
      loop_control:
        label: "{{ item }}"
  tags: ['microsoft']
