- name: Microsfot linux signing key present
  apt_key: 
    url: https://packages.microsoft.com/keys/microsoft.asc
    id: BC528686B50D79E339D3721CEB3E94ADBE1229CF
    state: present

- name: add Microsoft repo
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main"
    filename: "microsoft-edge.list"
    state: present
    update_cache: True

- name: add VS Code repo
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/code stable main"
    filename: "microsoft-vscode.list"
    state: present
    update_cache: True

- name: Install MS Edge and VS Code from repository
  apt:
    state: latest
    pkg: 
      - microsoft-edge-stable
      - code
