---
# https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/
- name: ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - bash-completion
      - ca-certificates
      - curl
    state: present

- name: install kubernetes apt key
  get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key
    dest: /usr/share/keyrings/kubernetes-archive-keyring.asc
    mode: 0644
    force: true

- name: add kubernetes repo
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /"
    filename: kubectl
    state: present
    update_cache: true

- name: install kubectl
  apt:
    name:
      - kubectl
    state: latest
