---
- name: ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - bash-completion
      - ca-certificates
      - curl
    state: present

- name: install kubernetes apt key
  get_url:
    #url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    url: https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key
    dest: /usr/share/keyrings/kubernetes-archive-keyring.asc
    mode: 0644
    force: true

# https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/
- name: add kubernetes repo
  apt_repository:
#    repo: "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.asc] https://apt.kubernetes.io/ kubernetes-xenial main"
    repo: "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /"
    filename: kubectl
    state: present
    update_cache: true

- name: install kubectl
  apt:
    name:
      - kubectl
    state: latest

#- name: Check if Kubectl auto-complete is enabled
#  stat:
#    path: /etc/bash_completion.d/kubectl
#  register: kubectl_auto
#
#- name: Enable Kubectl auto-complete for all users
#  shell: kubectl completion bash | sudo tee /etc/bash_completion.d/kubectl > /dev/null
#  when: kubectl_auto.stat.exists == False
