---
- name: disable systemd-resolved
  systemd:
    name: systemd-resolved.service
    enabled: false
    state: stopped

- name: add dns=default to /etc/NetworkManager/NetworkManager.conf
  lineinfile:
    firstmatch: true
    path: "/etc/NetworkManager/NetworkManager.conf"
    insertafter: '[main]'
    line: "dns=default"
  register: dns_default_status
  notify: restart network manager

- name: remove /etc/resolv.conf
  file:
    path: /etc/resolv.conf
    state: absent
  when: dns_default_status.changed == 'true'

- name: Re-enable systemd-resolved after disabling local dns
  systemd:
    name: systemd-resolved.service
    enabled: true
    state: started


# use handler instead
# - name: restart network-manager systemd-resolved
#   systemd:
#     name: NetworkManager.service
#     enabled: true
#     state: restarted
#   when: dns_default_status.changed == 'true'
