---
- block:
    - name: add DNSStubListener=no to /etc/systemd/resolved.conf
      lineinfile:
        firstmatch: true
        path: "/etc/systemd/resolved.conf"
        insertafter: "EOF"
        line: "DNSStubListener=no"
        state: present
      register: dns_default_status

    - name: print dns_default_status
      debug:
        var: dns_default_status.changed

    - name: restart network manager
      systemd:
        name: NetworkManager.service
        enabled: true
        state: restarted
      when: dns_default_status.changed

    - name: restart systemd resolved
      systemd:
        name: systemd-resolved.service
        enabled: true
        state: restarted
      when: dns_default_status.changed

    - name: Ensure DNS resolution is functional before continuing
      command: "dig example.com +short"
      register: dns_check
      retries: 10
      delay: 3
      until: dns_check.rc == 0
      when: dns_default_status.changed
  tags: ['disable-local-dns']
