---
- name: Add hashicorp key
  apt_key: 
    url: https://apt.releases.hashicorp.com/gpg
    id: E8A032E094D8EB4EA189D270DA418C88A3219F7B
    state: present

- name: Add hashicorp repo
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    filename: hashicorp
    state: present
    update_cache: True

- name: Install terraform and vagrant
  apt:
    state: present
    pkg:
      - terraform
      - vagrant
