---
# https://developer.hashicorp.com/vault/install#linux
- block:
    - name: add hashicorp key
      get_url:
        url: "https://apt.releases.hashicorp.com/gpg"
        dest: /usr/share/keyrings/hashicorp-archive-keyring.asc
        mode: 0644
        force: true

    - name: determine Hashicorp repo codename
      ansible.builtin.set_fact:
        hashicorp_codename: >-
          {{
            'noble'
            if ansible_facts.distribution_release == 'resolute'
            else ansible_facts.distribution_release
          }}

    - name: add hashicorp repo
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/hashicorp-archive-keyring.asc] https://apt.releases.hashicorp.com {{ hashicorp_codename }} main"
        filename: hashicorp
        state: present
        update_cache: true

    - name: set_fact hashicorp packages list
      set_fact:
        hashicorp_packages:
          - terraform
          - vagrant
          - vault

    - name: register hashicorp packages
      apt:
        state: latest
        name: "{{ hashicorp_packages }}"
      register: _apt_hashicorp_result

    - name: display hashicorp packages
      debug:
        msg: "{{ hashicorp_packages }}"

    - name: hashicorp packages | show what changed
      debug:
        msg: "{{ _apt_hashicorp_result.stdout_lines }}"
      when: _apt_hashicorp_result.changed

  tags: ['hashicorp']
