---
- name: add hashicorp key
  get_url:
    url: "https://apt.releases.hashicorp.com/gpg"
    dest: /usr/share/keyrings/hashicorp-archive-keyring.asc
    mode: 0644
    force: true

- name: add hashicorp repo
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/hashicorp-archive-keyring.asc] https://apt.releases.hashicorp.com noble main"
    filename: hashicorp
    state: present
    update_cache: true

- name: install terraform, vagrant, and vault
  apt:
    state: present
    pkg:
      - terraform
      - vagrant
      - vault
