---
- name: Detect physical and Wi-Fi interfaces (ignore virtual)
  set_fact:
    ntp_interfaces: >-
      {{ ansible_interfaces
        | reject('match', '^lo$|^docker.*|^br-.*|^veth.*|^virbr.*|^vmnet.*|^tap.*|^tun.*')
        | select('match', '^e.*|^en.*|^eth.*|^wlan.*|^wifi.*|^wl.*')
        | list }}

- name: Debug discovered interfaces
  debug:
    var: ntp_interfaces

- name: Write .network files with UseNTP per interface
  copy:
    dest: "/etc/systemd/network/10-{{ item }}-ntp.network"
    content: |
      [Match]
      Name={{ item }}

      [Network]
      DHCP=ipv4

      [DHCP]
      UseNTP=true
    owner: root
    group: root
    mode: '0644'
  loop: "{{ ntp_interfaces }}"

# Immediately restart and validate services — no handler dependency
- name: Restart systemd-networkd now
  systemd:
    name: systemd-networkd
    state: restarted
    enabled: true
    daemon_reload: true

- name: Wait for systemd-networkd to settle
  wait_for:
    path: /run/systemd/netif/links
    state: present
    timeout: 10

- name: Restart systemd-timesyncd now
  systemd:
    name: systemd-timesyncd
    state: restarted
    enabled: true

- name: Wait for systemd-timesyncd to become active
  shell: systemctl is-active systemd-timesyncd
  register: timesyncd_status
  until: timesyncd_status.stdout == "active"
  retries: 8
  delay: 2
  changed_when: false

- name: Wait for system clock to sync via NTP
  shell: timedatectl show -p NTPSynchronized --value
  register: ntp_sync
  until: ntp_sync.stdout == "yes"
  retries: 8
  delay: 5
  changed_when: false

