---
- name: ensure apt-transport-https is installed
  apt:
    pkg: apt-transport-https
    state: present

- name: add grafana GPG key
  apt_key:
    url: https://packagecloud.io/gpg.key
    state: present

- name: add grafana repository
  apt_repository:
    repo: deb https://packagecloud.io/grafana/stable/debian/ jessie main
    state: present
    update_cache: yes

- name: install grafana
  apt:
    pkg: grafana
    state: "{{ grafana_install_state }}"

- name: copy grafana configuration file
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: restart grafana

- name: start and enable grafana
  service:
    name: grafana-server
    state: started
    enabled: yes
