---
- name: Add Vivaldi apt key
  get_url:
    url: https://repo.vivaldi.com/archive/linux_signing_key.pub
    dest: /usr/share/keyrings/vivaldi-browser.asc
    mode: '0644'
    force: true

- name: Add Vivaldi apt repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/vivaldi-browser.asc] https://repo.vivaldi.com/archive/deb/ stable main"
    filename: vivaldi
    state: present
    update_cache: True

- name: Install Vivaldi from repository
  apt:
    name: vivaldi-stable
    state: latest
