#cloud-config
package_update: true
package_upgrade: true

packages:
  - ubuntu-desktop
  - network-manager
  - xrdp

chpasswd:
  list: |
    ubuntu:ubuntu
  expire: False  # Ensure the password does not expire

runcmd:
  - sudo systemctl set-default graphical.target
  - sudo reboot

final_message: "Ubuntu Desktop installation completed. System will reboot."
