### DCONF_PATH: /org/gnome/shell/
[/]
command-history=['libreoffice']
disable-user-extensions=true
edge-tiling=false
enabled-extensions=['ding@rastersoft.com', 'ubuntu-dock@ubuntu.com', 'tiling-assistant@ubuntu.com']
experimental-features=['x11-randr-fractional-scaling', 'scale-monitor-framebuffer']
favorite-apps=['org.keepassxc.KeePassXC.desktop', 'Alacritty.desktop', 'google-chrome.desktop', 'firefox.desktop', 'signal-desktop.desktop', 'brave-browser.desktop', 'microsoft-edge.desktop', 'org.gnome.Nautilus.desktop', 'code.desktop', 'chromium_chromium.desktop', 'mullvad-browser.desktop']
last-selected-power-profile='power-saver'
remember-mount-password=false
welcome-dialog-last-shown-version='42.2'

[app-folders]
folder-children=['Utilities', 'Sundry', 'YaST']

[app-folders/folders/Pardus]
categories=['X-Pardus-Apps']
name='X-Pardus-Apps.directory'
translate=true

[app-folders/folders/Sundry]
apps=['alacarte.desktop', 'authconfig.desktop', 'ca.desrt.dconf-editor.desktop', 'fedora-release-notes.desktop', 'firewall-config.desktop', 'flash-player-properties.desktop', 'gconf-editor.desktop', 'gnome-abrt.desktop', 'gnome-power-statistics.desktop', 'ibus-setup-anthy.desktop', 'ibus-setup.desktop', 'ibus-setup-hangul.desktop', 'ibus-setup-libbopomofo.desktop', 'ibus-setup-libpinyin.desktop', 'ibus-setup-m17n.desktop', 'ibus-setup-typing-booster.desktop', 'im-chooser.desktop', 'itweb-settings.desktop', 'jhbuild.desktop', 'javaws.desktop', 'java-1.7.0-openjdk-jconsole.desktop', 'java-1.7.0-openjdk-policytool.desktop', 'log4j-chainsaw.desktop', 'log4j-logfactor5.desktop', 'nm-connection-editor.desktop', 'orca.desktop', 'setroubleshoot.desktop', 'system-config-date.desktop', 'system-config-firewall.desktop', 'system-config-keyboard.desktop', 'system-config-language.desktop', 'system-config-printer.desktop', 'system-config-users.desktop', 'vino-preferences.desktop']
categories=['X-GNOME-Sundry']
name='X-GNOME-Sundry.directory'
translate=true

[app-folders/folders/Utilities]
apps=['org.gnome.baobab.desktop', 'deja-dup-preferences.desktop', 'eog.desktop', 'evince.desktop', 'org.gnome.FileRoller.desktop', 'gnome-calculator.desktop', 'gnome-dictionary.desktop', 'org.gnome.Characters.desktop', 'org.gnome.DiskUtility.desktop', 'org.gnome.font-viewer.desktop', 'org.gnome.Terminal.desktop', 'org.gnome.Screenshot.desktop', 'gnome-system-log.desktop', 'gnome-system-monitor.desktop', 'gnome-tweak-tool.desktop', 'gucharmap.desktop', 'seahorse.desktop', 'vinagre.desktop', 'yelp.desktop']
categories=['X-GNOME-Utilities']
name='X-GNOME-Utilities.directory'
translate=true

[app-folders/folders/YaST]
categories=['X-SuSE-YaST']
name='suse-yast.directory'
translate=true

[background]
color-shading-type='solid'
picture-options='zoom'
picture-uri='file:///usr/share/backgrounds/Manhattan_Sunset_by_Giacomo_Ferroni.jpg'
picture-uri-dark='file:///usr/share/backgrounds/Optical_Fibers_in_Dark_by_Elena_Stravoravdi.jpg'
primary-color='#000000'
secondary-color='#000000'

[extensions/dash-to-dock]
dash-max-icon-size=38
preferred-monitor=-2
preferred-monitor-by-connector='primary'

[extensions/ding]
check-x11wayland=true
icon-size='large'
start-corner='top-right'

[extensions/tiling-assistant]
active-window-hint-color='rgb(211,70,21)'
last-version-installed=46
move-favorite-layout-mod=0
overridden-settings={'org.gnome.mutter.edge-tiling': <@mb nothing>, 'org.gnome.mutter.keybindings.toggle-tiled-left': <@mb nothing>, 'org.gnome.mutter.keybindings.toggle-tiled-right': <@mb nothing>}

[input-sources]
per-window=false
sources=[('xkb', 'us')]
xkb-options=@as []

[interface]
color-scheme='prefer-dark'
enable-animations=false
gtk-im-module='gtk-im-context-simple'
gtk-theme='Yaru-dark'
icon-theme='Yaru'
show-battery-percentage=true
toolkit-accessibility=false

[keybindings]
show-screenshot-ui=['Print']
toggle-tiled-left=@as []
toggle-tiled-right=@as []

[peripherals/mouse]
speed=0.53676470588235303

[peripherals/touchpad]
click-method='fingers'
speed=0.81617647058823528
two-finger-scrolling-enabled=true

[privacy]
disable-microphone=false
old-files-age=uint32 30
recent-files-max-age=-1
report-technical-problems=true

[screensaver]
color-shading-type='solid'
lock-delay=uint32 3600
lock-enabled=false
picture-options='zoom'
picture-uri='file:///usr/share/backgrounds/Optical_Fibers_in_Dark_by_Elena_Stravoravdi.jpg'
primary-color='#000000'
secondary-color='#000000'
ubuntu-lock-on-suspend=false

[search-providers]
disable-external=true
disabled=['org.gnome.Nautilus.desktop', 'org.gnome.Calculator.desktop', 'org.gnome.Calendar.desktop', 'seahorse.desktop', 'org.gnome.Terminal.desktop']
sort-order=['org.gnome.Contacts.desktop', 'org.gnome.Documents.desktop', 'org.gnome.Nautilus.desktop']

[session]
idle-delay=uint32 900

[sound]
allow-volume-above-100-percent=false
event-sounds=true

[wm/preferences]
mouse-button-modifier='<Alt>'
resize-with-right-button=true

[world-clocks]
locations=@av []

### DCONF_PATH: /org/gnome/desktop/interface/
[/]
color-scheme='prefer-dark'
enable-animations=false
gtk-im-module='gtk-im-context-simple'
gtk-theme='Yaru-dark'
icon-theme='Yaru'
show-battery-percentage=true
toolkit-accessibility=false

### DCONF_PATH: /org/gnome/desktop/peripherals/
[mouse]
speed=0.53676470588235303

[touchpad]
click-method='fingers'
speed=0.81617647058823528
two-finger-scrolling-enabled=true

### DCONF_PATH: /org/gnome/desktop/wm/
[preferences]
mouse-button-modifier='<Alt>'
resize-with-right-button=true

### DCONF_PATH: /org/gnome/desktop/input-sources/
[/]
per-window=false
sources=[('xkb', 'us')]
xkb-options=@as []

### DCONF_PATH: /org/gnome/desktop/background/
[/]
color-shading-type='solid'
picture-options='zoom'
picture-uri='file:///usr/share/backgrounds/Manhattan_Sunset_by_Giacomo_Ferroni.jpg'
picture-uri-dark='file:///usr/share/backgrounds/Optical_Fibers_in_Dark_by_Elena_Stravoravdi.jpg'
primary-color='#000000'
secondary-color='#000000'

### DCONF_PATH: /org/gnome/desktop/screensaver/
[/]
color-shading-type='solid'
lock-delay=uint32 3600
lock-enabled=false
picture-options='zoom'
picture-uri='file:///usr/share/backgrounds/Optical_Fibers_in_Dark_by_Elena_Stravoravdi.jpg'
primary-color='#000000'
secondary-color='#000000'
ubuntu-lock-on-suspend=false

### DCONF_PATH: /org/gnome/desktop/privacy/
[/]
disable-microphone=false
old-files-age=uint32 30
recent-files-max-age=-1
report-technical-problems=true

### DCONF_PATH: /org/gnome/desktop/search-providers/
[/]
disable-external=true
disabled=['org.gnome.Nautilus.desktop', 'org.gnome.Calculator.desktop', 'org.gnome.Calendar.desktop', 'seahorse.desktop', 'org.gnome.Terminal.desktop']
sort-order=['org.gnome.Contacts.desktop', 'org.gnome.Documents.desktop', 'org.gnome.Nautilus.desktop']

### DCONF_PATH: /org/gnome/desktop/session/
[/]
idle-delay=uint32 900

### DCONF_PATH: /org/gnome/desktop/sound/
[/]
allow-volume-above-100-percent=false
event-sounds=true

### DCONF_PATH: /org/gnome/mutter/keybindings/
[/]
show-screenshot-ui=['Print']
toggle-tiled-left=@as []
toggle-tiled-right=@as []

### DCONF_PATH: /org/gnome/settings-daemon/
[peripherals/keyboard]
numlock-state='off'

[plugins/color]
night-light-enabled=true
night-light-temperature=uint32 4700

[plugins/media-keys]
area-screenshot=['Print']
calculator=@as []
control-center=@as []
custom-keybindings=['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/']
home=['<Super>e']
screenshot=@as []
terminal=['<Super>x']
volume-down=['F7']
volume-up=['F8']

[plugins/media-keys/custom-keybindings/custom0]
binding='<Primary><Alt>q'
command='/usr/bin/blank.sh'
name='Turn off monitor'

[plugins/media-keys/custom-keybindings/custom1]
binding='<Super>c'
command='alacritty'
name='alacritty'

[plugins/power]
idle-dim=false
power-button-action='suspend'
sleep-inactive-ac-timeout=3600
sleep-inactive-ac-type='nothing'
sleep-inactive-battery-timeout=3600

### DCONF_PATH: /org/gnome/terminal/
[legacy]
schema-version=uint32 3
theme-variant='system'

[legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9]
audible-bell=false
background-color='rgb(23,20,33)'
background-transparency-percent=0
bold-is-bright=false
default-size-columns=87
default-size-rows=55
font='Monospace 13'
foreground-color='rgb(208,207,204)'
login-shell=false
palette=['rgb(0,0,0)', 'rgb(170,0,0)', 'rgb(0,170,0)', 'rgb(170,85,0)', 'rgb(95,95,154)', 'rgb(170,0,170)', 'rgb(0,170,170)', 'rgb(170,170,170)', 'rgb(85,85,85)', 'rgb(255,85,85)', 'rgb(85,255,85)', 'rgb(255,255,85)', 'rgb(85,85,255)', 'rgb(255,85,255)', 'rgb(85,255,255)', 'rgb(255,255,255)']
scroll-on-output=true
scrollback-lines=100000
use-theme-colors=false
use-theme-transparency=false
use-transparent-background=false
