---
- name: set_fact dev tools packages list
  set_fact:
    dev_packages:
      - build-essential
      - gcc
      - git
      - gitk
      - golang
      - gron
      - httpie
      - jq
      - make
      - miller
      - pipx
      - python3-venv
      - shellcheck
      - shfmt
      - universal-ctags

- name: register dev tools packages
  apt:
    state: latest
    name: "{{ dev_packages }}"
  register: _apt_dev_result

- name: display dev tools
  debug:
    msg: "{{ dev_packages }}"

- name: dev tools | show what changed
  debug:
    msg: "{{ _apt_dev_result.stdout_lines }}"
  when: _apt_dev_result.changed
