---
- name: update uv to latest
  command: "{{ home_dir }}/.local/bin/uv self update"
  register: _uv_update
  changed_when: "'already on version' not in _uv_update.stderr"
  become: false

- name: upgrade all uv tools
  command: "{{ home_dir }}/.local/bin/uv tool upgrade --all"
  register: _uv_upgrade_all
  changed_when: "'Nothing to upgrade' not in _uv_upgrade_all.stderr"
  become: false
