---
- name: check if uv is installed
  stat:
    path: "{{ home_dir }}/.local/bin/uv"
  register: _uv_installed
  become: false

- name: download uv installer
  get_url:
    url: https://astral.sh/uv/install.sh
    dest: /tmp/uv-install.sh
    mode: '0755'
  when: not _uv_installed.stat.exists
  become: false

- name: install uv
  command: /tmp/uv-install.sh
  when: not _uv_installed.stat.exists
  become: false

- name: update uv to latest
  command: uv self update
  register: _uv_update
  changed_when: "'Updated' in _uv_update.stdout"
  when: _uv_installed.stat.exists
  become: false

- name: define uv tool packages
  set_fact:
    uv_packages:
      - bandit
      - black
      - cfn-lint
      - coverage
      - flake8
      - mypy
      - pre-commit
      - pytest
      - ruff
      - yamlfmt
      - yamllint

- name: uv tool packages to manage
  debug:
    msg: "{{ uv_packages }}"

- name: check installed uv tools
  command: uv tool list
  register: _uv_tools
  changed_when: false
  become: false

- name: install uv tools
  command: uv tool install {{ item }}
  loop: "{{ uv_packages }}"
  when: item not in _uv_tools.stdout
  become: false

- name: upgrade all uv tools
  command: uv tool upgrade --all
  register: _uv_upgrade_all
  changed_when: "'Updated' in _uv_upgrade_all.stdout"
  become: false
