---
- name: Ensure old versions of Docker are not installed.
  package:
    name:
      - docker
      - docker-engine
    state: absent

- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg2
      - lsb-release
    state: present

- name: Add Docker apt repository key.
  get_url:
    url: "{{ docker_apt_gpg_key }}"
    dest: /usr/share/keyrings/docker.asc
    mode: '0644'
    force: true

- name: Ensure curl is present (on older systems without SNI).
  package: name=curl state=present
  #when: add_repository_key is failed

- name: Add Docker apt key (alternative for older systems without SNI).
  shell: >
    curl -sSL {{ docker_apt_gpg_key }} | sudo apt-key add -
  args:
    warn: False
  #when: add_repository_key is failed

- name: Add Docker repository.
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker.asc] https://download.docker.com/linux/ubuntu jammy stable"
    filename: docker
    state: present
    update_cache: True
