---
- name: packages | apt update && apt dist-upgrade *MAY TAKE A LONG TIME*
  apt:
    update_cache: true
    upgrade: dist

# keep alphabetically ordered
- name: packages | define base packages
  set_fact:
    base_packages:
      - bat
      - btop
      - clamav
      - clamav-daemon
      - curl
      - eza
      - fd-find
      - gimp
      - graphviz
      - htop
      - iperf3
      - meld
      - net-tools
      - nmap
      - okular
      - p7zip
      - qemu-system-x86
      - ranger
      - rclone
      - ripgrep
      - rtorrent
      - silversearcher-ag
      - sshfs
      - tcpdump
      - tmux
      - tree
      - ufw
      - unzip
      - vim-gtk3  # install by github and compile
      - vlc
      - xclip
      - zoxide

- name: packages | install standard additions to the base install
  apt:
    state: latest
    name: "{{ base_packages }}"
  register: _apt_result

- name: packages | managed package list
  debug:
    msg: "{{ base_packages }}"

- name: packages | show what changed
  debug:
    msg: "{{ _apt_result.stdout_lines }}"
  when: _apt_result.changed

- name: packages | apt autoremove & autoclean
  apt:
    autoremove: true
    autoclean: true

- name: packages | enable clamav service
  systemd:
    name: clamav-daemon
    enabled: true
    state: started
