---
- name: Ensure git is installed.
  apt:
    name: "git"
    state: present

- name: Copy ssh-default-banners from repository
  git:
    repo: "https://github.com/richlamdev/ssh-default-banners.git"
    dest: "/home/{{ local_username }}/git/ssh-default-banners/"
    update: no

- name: Copy ansible-desktop-ubuntu from repository
  git:
    repo: "https://github.com/richlamdev/ansible-desktop-ubuntu.git"
    dest: "/home/{{ local_username }}/git/ansible-desktop-ubuntu"
    update: no

- name: Copy pagerduty from repository
  git:
    repo: "https://github.com/richlamdev/pagerduty_client.git"
    dest: "/home/{{ local_username }}/git/pagerduty_client"
    update: no

- name: Copy ansible-misc from repository
  git:
    repo: "https://github.com/richlamdev/ansible-misc.git"
    dest: "/home/{{ local_username }}/git/ansible-misc"
    update: no

- name: Copy misc from repository
  git:
    repo: "https://github.com/richlamdev/misc.git"
    dest: "/home/{{ local_username }}/git/misc"
    update: no

- name: Change ownership of git repos
  file:
    path: "/home/{{ local_username }}/git"
    owner: "{{ local_username }}"
    group: "{{ local_username }}"
    state: directory
    recurse: yes
