---
- name: Manage SSH configurations
  block:
    - name: Ensure /etc/ssh/sshd_config.d exists
      ansible.builtin.file:
        path: /etc/ssh/sshd_config.d
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Remove unmanaged files from /etc/ssh/sshd_config.d
      ansible.builtin.find:
        paths: /etc/ssh/sshd_config.d/
        file_type: file
        patterns: '*'
      register: sshd_config_d_files

    - name: Remove unmanaged sshd files
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ sshd_config_d_files.files }}"
      when: item.path | basename != 'sshd_config.conf'
      loop_control:
        label: "{{ item.path }}"
      notify: reload sshd

    - name: Copy managed sshd_config.conf
      ansible.builtin.copy:
        src: sshd_config.conf
        dest: /etc/ssh/sshd_config.d/sshd_config.conf
        owner: root
        group: root
        mode: '0644'
      notify: reload sshd


    - name: Ensure /etc/ssh/ssh_config.d exists
      ansible.builtin.file:
        path: /etc/ssh/ssh_config.d
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Remove unmanaged files from /etc/ssh/ssh_config.d
      ansible.builtin.find:
        paths: /etc/ssh/ssh_config.d/
        file_type: file
        patterns: '*'
      register: ssh_config_d_files

    - name: Remove unmanaged ssh files
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ ssh_config_d_files.files }}"
      when: item.path | basename != 'ssh_config.conf'
      loop_control:
        label: "{{ item.path }}"
      notify: reload sshd

    - name: Copy managed ssh_config.conf
      ansible.builtin.copy:
        src: ssh_config.conf
        dest: /etc/ssh/ssh_config.d/ssh_config.conf
        owner: root
        group: root
        mode: '0644'
      notify: reload sshd
  tags: ['ssh-configs']
