---
# execute this role as normal user, to minimize affecting the system files/dependencies
- name: install urllib3 with pip
  pip:
    state: latest
    extra_args: --user
    executable: pip3
    name:
      - urllib3

- name: install bandit, boto3, black, bottle, flake8, glances, pre-commit, pytest, ruff, yamllint with pipx
  community.general.pipx:
    state: latest
    name: "{{ item }}"
    install_deps: true
  loop:
    - bandit
    - boto3
    - black
    - bottle
    - flake8
    - glances
    - pre-commit
    - pytest
    - ruff
    - yamllint

- name: Check if pipx path is present
  shell: test -d ~/.local/bin && echo "Pipx ensurepath executed" || echo "Pipx ensurepath not executed"
  register: pipx_ensurepath_output
  changed_when: false
  ignore_errors: true

- name: Execute pipx ensurepath, if required
  command: pipx ensurepath
  when: pipx_ensurepath_output.rc != 0
